apiVersion: v1
description: "Feast Core: Feature registry for Feast."
name: feast-core
version: 0.26.0
appVersion: 0.26.0
keywords:
- machine learning
- big data
- mlops
home: https://github.com/feast-dev/feast-java
